# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: pointnav
  - /habitat/dataset/pointnav: hm3d
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: depth_agent
  - _self_

habitat:
  environment:
    max_episode_steps: 500
  simulator:
    agents:
      main_agent:
        height: 0.88
        radius: 0.18
        sim_sensors:
          depth_sensor:
            type: HabitatSimDepthSensor
            height: 640
            width: 360
            position:
              - 0.0
              - 1.31
              - 0.0
            orientation:
              - 0.0
              - 0.0
              - 0.0
            hfov: 42
            sensor_subtype: PINHOLE
            noise_model: None
            noise_model_kwargs: { }
            min_depth: 0.5
            max_depth: 5.0
            normalize_depth: true
    habitat_sim_v0:
      gpu_device_id: 0
      allow_sliding: False
